/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 helicopter.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/helicopter.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[1.389, -0.221, -1.267]} scale={0.065}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.black} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.elise} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials.glass} />
        <mesh geometry={nodes.Cube001_4.geometry} material={materials.rotor} />
      </group>
    </group>
  )
}

useGLTF.preload('/helicopter.glb')
